const std = @import("std");

pub const EntityType = enum {
    // Characters and Objects are both Things.
    Thing,
    // Areas and Structures are both Grids. The main difference is that Structures can have a Location.
    Area,
    Structure,
};

/// the raw name of an entity, used for display.
pub const Name = struct {
    name: []const u8,
};

/// Specific keywords to use for a thing.
/// Normally, keywords are auto-generated by splitting the name
/// and possibly adding extra things like race name,
/// but these will be added on top of that.
pub const Keywords = struct {
    keywords: std.ArrayList([]const u8),
};

/// A sizable description of an entity, when looked at.
pub const Description = struct {
    description: []const u8,
};

/// Entities often have stats. These are defined in Lua but stored here.
pub const Stats = struct {
    /// Base stats are defined in Lua using string ids.
    /// The stat values are stored here.
    stats: std.StringHashMap(i64),
};

/// Some stats are derived, like max health or carry capacity.
/// The calculations are handled in Lua, but stored on entities.
pub const DerivedData = struct {
    /// This is a flag to indicate whether the derived data needs to be recalculated.
    dirty: bool,
    // Still wondering if this should be f64 or i64.
    value: i64,
};

/// The actual derived stats are defined in lua, but they're stored here.
pub const Deriveds = struct {
    stats: std.StringHashMap(DerivedData),
};

/// Meters like health, mana, stamina, etc, defined in Lua but stored here.
/// The value ranges from 0.0 to 1.0
pub const Meters = struct {
    meters: std.StringHashMap(f64),
};

/// Commmodities are "items" that a entities can have in arbitrary amounts,
/// like gold, crafting materials, or even possibly abstract things like "elven favor".
/// They're defined in Lua but stored here.
pub const Commodities = struct {
    commodities: std.StringHashMap(i64),
};
